name = "Hugo Blogging Starter"
license = "MIT"
licenselink = "https://github.com/sharadcodes/hugo-blogging-starter/blob/master/LICENSE"
description = ""
homepage = "https://github.com/sharadcodes/hugo-blogging-starter/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Sharad Raj"
  homepage = "https://codingindian.codes"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""